// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ratting.Persistance;

#nullable disable

namespace Ratting.Persistance.Migrations
{
    [DbContext(typeof(RattingDbContext))]
    [Migration("20240629102542_add_money")]
    partial class add_money
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Ratting.Domain.Player", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.HasKey("name");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
